### ISSUE TITLE
Timeout  while running Calvin

### ISSUE THREAD

**Issue by CES-dengzeyuan** [sam1016yu/DB-Exp-Sensitivity#1]
Hi~ What an excellent job!

I use 6 Docker VMs to simulate a cluster. Following your instructions, I built the project and ensured password-free login for machines in the cluster. Everything went well. 

But in the last step (the python script test), I found that a timeout error occurred. Timeout occurs in both single-node (node0) and multi-node clusters scenarios.

<img width="807" alt="截屏2022-06-10 21 40 40" src="https://user-images.githubusercontent.com/46039524/173078366-288b0930-bbaa-4ad9-a27b-2b386af65cab.png">

<img width="822" alt="截屏2022-06-10 21 41 56" src="https://user-images.githubusercontent.com/46039524/173078612-8f5273c9-d17b-4436-8187-321ce4edc6d3.png">

**Comment by sam1016yu** [comment]
This looks like the timeout I introduced. See [here](https://github.com/sam1016yu/DB-Exp-Sensitivity/blob/98f5db93710d1e08ee9712032bbe256414896e3c/calvin/test_calvin.py#L50)

**Comment by CES-dengzeyuan** [comment]
So I should enlarge t_out to solve the problem, am I right?

**Comment by sam1016yu** [comment]
Well, this timeout is not a "problem" per se. If you run Clavin without the python wrapper script, you will see what happened: it keeps running. This timeout is introduced to manually terminate each experiment run. You can of course change this timeout value as you wish.

**Comment by CES-dengzeyuan** [comment]
Thanks~
